name: CI/CD PR Request
on:
  pull_request:
    branches:
      - main
      - develop
      - staging
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node.js Setup
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Lint
        working-directory: ./functions
        run: npm run lint
        # We can put Code Reviewers, AI tools, PR reviewers etc. here
